apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil42
  template:
    metadata:
      labels:
        app: wil42
    spec:
      containers:
        - name: wil42
          image: wil42/playground:v1
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: wil42
spec:
  selector:
    app: wil42
  ports:
    - port: 8888
      targetPort: 8888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil42-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: will-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wil42
            port:
              number: 8888
