apiVersion: apps/v1
kind: Deployment
metadata:
  name: will42
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will42
  template:
    metadata:
      labels:
        app: will42
    spec:
      containers:
        - name: will42
          image: wil42/playground:v1
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: will42
spec:
  selector:
    app: will42
  ports:
    - port: 80
      targetPort: 8888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: will42-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: will42.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: will42
            port:
              number: 8888
